// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package crawltest contains autogenerated mocks.
package crawltest

import "github.com/johnstcn/gocrawl/pkg/crawl"
import "github.com/stretchr/testify/mock"

// Crawler is an autogenerated mock type for the Crawler type
type Crawler struct {
	mock.Mock
}

// Crawl provides a mock function with given fields: j
func (mockerySelf *Crawler) Crawl(j *crawl.Job) (crawl.Result, error) {
	ret := mockerySelf.Called(j)

	var r0 crawl.Result
	if rf, ok := ret.Get(0).(func(*crawl.Job) crawl.Result); ok {
		r0 = rf(j)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crawl.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*crawl.Job) error); ok {
		r1 = rf(j)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
